In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [5]:
df=pd.read_parquet("/home/ec2-user/SageMaker/sensor-imputation-thesis/src/sensor_imputation_thesis/nadire/9missingcolsdata.parquet")

In [6]:
df.describe()

,time,fr_eng,te_exh_cyl_out__0,te_exh_cyl_out__1,te_exh_cyl_out__2,te_exh_cyl_out__3,te_exh_cyl_out__4,te_exh_cyl_out__5,te_exh_cyl_out__6,pd_air_ic__0,...,pr_cyl_max__2,pr_cyl_max__3,pr_cyl_max__4,pr_cyl_max__5,pr_cyl_max__6,pr_cyl_max__7,pr_cyl_max__8,pr_cyl_max__9,pr_cyl_max__10,pr_cyl_max__11
count,430897,413587.000000,413587.000000,413587.000000,413587.000000,413587.000000,413587.000000,413587.000000,0.0,413586.000000,...,2.447890e+05,2.447890e+05,2.447890e+05,2.447890e+05,0.0,0.0,0.0,0.0,0.0,0.0
mean,2024-04-02 18:06:08.558797568,0.579343,467.367613,462.747391,474.538027,478.842531,468.562370,484.326231,NaN,1029.130580,...,1.449609e+07,1.451113e+07,1.449665e+07,1.448251e+07,NaN,NaN,NaN,NaN,NaN,NaN
min,2023-10-31 00:00:00,-0.691667,287.150000,288.150000,289.150000,289.150000,290.150000,288.150000,NaN,0.000000,...,2.950000e+06,2.970000e+06,2.990000e+06,2.810000e+06,NaN,NaN,NaN,NaN,NaN,NaN
25%,2024-01-14 03:42:00,0.000000,322.150000,322.150000,325.150000,326.150000,325.150000,326.150000,NaN,0.000000,...,1.272000e+07,1.277000e+07,1.276000e+07,1.269000e+07,NaN,NaN,NaN,NaN,NaN,NaN
50%,2024-03-30 02:38:00,0.881667,543.150000,537.150000,550.150000,561.150000,541.150000,568.150000,NaN,1000.000000,...,1.464000e+07,1.466000e+07,1.467000e+07,1.466000e+07,NaN,NaN,NaN,NaN,NaN,NaN
75%,2024-06-15 02:21:00,1.031667,569.150000,559.150000,582.150000,583.150000,568.150000,596.150000,NaN,2000.000000,...,1.641000e+07,1.643000e+07,1.642000e+07,1.642000e+07,NaN,NaN,NaN,NaN,NaN,NaN
max,2024-09-30 23:59:00,1.161667,633.150000,615.150000,632.150000,641.150000,623.150000,657.150000,NaN,3000.000000,...,1.912000e+07,1.922000e+07,1.927000e+07,1.928000e+07,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.491547,117.123678,114.966705,120.058149,123.411919,115.284706,127.981016,NaN,932.841699,...,2.364256e+06,2.356933e+06,2.398391e+06,2.425657e+06,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df["te_exh_cyl_out__0"][:10]

0    524.15
1    524.15
2    525.15
3    525.15
4    525.15
5    525.15
6    525.15
7    525.15
8    525.15
9    525.15
Name: te_exh_cyl_out__0, dtype: float64

In [ ]:
scaler=StandardScaler()